/*
    module  : error.h
    version : 1.2
    date    : 10/26/20
*/
enum {
    RIGHT_PARENTHESIS_EXPECTED,
    ILLEGAL_START_OF_SCAN_EXPR,
    TOO_MANY_INCLUDE_FILES,
    A_Z_EXPECTED,
    IS_EXPECTED,
    UNKNOWN_DIRECTIVE,
    EXCEEDING_ALTERNATIVE_RADIX,
    INTERNAL_ERROR_SELFREFERENCE,
    DYNAMIC_MEMORY_EXHAUSTED,
    INTERNAL_ERROR_CIRCULAR,
    INTERNAL_IN_READFACTOR,
    PASS_2_IDENTIFIER_EXPECTED,
    PASS_2_EQUAL_EXPECTED,
    NOT_OPEN_FOR_READING,
    STRING,
    CHARACTER,
    DEFINITION_EXPECTED,
    DIGIT_EXPECTED,
    NUMERIC_EXPECTED_IN_SET,
    RIGHT_BRACKET_EXPECTED,
    PARENTHESIS_NOT_IMPLEMENTED,
    WARNING_OVERWRITING_INBUILT,
    BYTE_VALUE_EXPECTED,
    WARNING_REDEFINITION,
    WARNING
};

void Warning(int num, char *str);
void Error(int num);
void ExpError(int num);
void ExecError(int num, char *op);
