/*
    module  : aux_decode.c
    version : 1.2
    date    : 10/26/20
*/
#include <stdio.h>
#include <time.h>
#include "data.h"

/*
mktime  T  ->  I
Converts a list T representing local time into a time I.
T is in the format generated by localtime.
*/
void aux_decode(struct tm *tm)
{
    data_t *cur;

    cur = stack->list;
    tm->tm_year = cur->num - 1900;
    cur = cur->next;
    tm->tm_mon = cur->num - 1;
    cur = cur->next;
    tm->tm_mday = cur->num;
    cur = cur->next;
    tm->tm_hour = cur->num;
    cur = cur->next;
    tm->tm_min = cur->num;
    cur = cur->next;
    tm->tm_sec = cur->num;
    cur = cur->next;
    tm->tm_isdst = cur->num;
    cur = cur->next;
    tm->tm_yday = cur->num;
    cur = cur->next;
    tm->tm_wday = cur->num;
}
