/*
    module  : do_mktime.c
    version : 1.2
    date    : 10/26/20
*/
#include <stdio.h>
#include <time.h>
#include <assert.h>
#include "data.h"
#include "ident.h"

void aux_decode(struct tm *tm);

/*
mktime  T  ->  I
Converts a list T representing local time into a time I.
T is in the format generated by localtime.
*/
void do_mktime()
{
    data_t *cur;
    struct tm tm;

    DEBUG(__FUNCTION__);
    assert(stack && stack->op == typ_list);
    aux_decode(&tm);
    cur = get(1);
    cur->op = typ_integer;
    cur->num = mktime(&tm);
    cur->next = stack->next;
    stack = cur;
}
